### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by perfect-network** [lizhongnian/ss-panel-v3-mod-node-connect#1]
‘’‘
loaded collections.OrderedDict
IPv6 support
INFO: ShadowsocksR 3.4.0 mod by esdeathlove
INFO: current process RLIMIT_NOFILE resource: soft 512000 hard 512000
INFO: loading config from user-config.json
2019-06-15 06:31:39 ERROR    auto_block.py:293 Traceback (most recent call last):
  File "/root/shadowsocks/auto_block.py", line 289, in thread_db
    db_instance.auto_block_thread()
  File "/root/shadowsocks/auto_block.py", line 50, in auto_block_thread
    import cymysql
ImportError: No module named cymysql

2019-06-15 06:31:39 INFO     util.py:49 loading libcrypto from libcrypto.so.10
2019-06-15 06:31:39 INFO     asyncdns.py:324 dns server: [('139.162.21.5', 53), ('139.162.27.5', 53), ('139.162.11.5', 53)]
2019-06-15 06:31:39 INFO     asyncdns.py:324 dns server: [('139.162.21.5', 53), ('139.162.27.5', 53), ('139.162.11.5', 53)]
2019-06-15 06:31:39 ERROR    db_transfer.py:872 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 864, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 290, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 51, in update_all_user
    import cymysql
ImportError: No module named cymysql

’‘’

运行环境：Centos7 linode
添加一句：‘’‘pip install cymysql’‘’
即可

**Comment by uubxs** [comment]
还有idna，一直都是要最后单独安装一下才行。
看到大佬回归了，能否空的时候帮更新下呢。另外能否问下大佬，发生了什么？
